import Head from "next/head";
import HomeLayout from "../layouts/homelayout";
import Navigation from "../components/navigation";
import hero from "../public/assets/homepage-1.jpg";
import Image from "next/image";
import { Carousel } from "react-responsive-carousel";
import HomeCarousel from "../components/carousel";

export default function Home(props) {
  return (
    <section>
      <Head>
        <title>Home thats the key</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{props.apiKey ? `hey there ${props.apiKey} thats the key!` : `hey its null`}</h1>
      <Navigation />

      <HomeCarousel />
    </section>
  );
}

export function getServerSideProps() {
  console.log(process.env.NEXT_PUBLIC_APIKEY, process.env.authDomain)
  return {
    props: {apiKey: (process.env.NEXT_PUBLIC_APIKEY ? process.env.NEXT_PUBLIC_APIKEY : null) },
  };
}

Home.PageLayout = HomeLayout;
