import Link from "next/link";
import Head from "next/head";
import HomeLayout from "../layouts/homelayout";
import Navigation from "../components/navigation";
import hero from "../public/assets/homepage-1.jpg";
import Image from "next/image";
import { Carousel } from "react-responsive-carousel";
import HomeCarousel from "../components/carousel";

function Home(props) {
  return (
    <section>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <HomeCarousel />
    </section>
  );
}
Home.PageLayout = HomeLayout;

export default Home;
